/**
 * Prompt and context building utilities for the generation pipeline.
 *
 * All hardcoded prompt strings are now configurable via the PromptTemplateConfig
 * parameter. Pass overrides to customize instructor-facing language.
 */

import type { PdfImage } from '@/lib/types/generation';
import type { AgentInfo, SceneGenerationContext } from './pipeline-types';

// ── Configurable template strings ──

export interface PromptTemplateConfig {
  /** Course context building */
  courseOutlineHeader?: string;
  currentPageMarker?: string;
  sameSessionWarning?: string;
  firstPageInstruction?: string;
  lastPageInstruction?: string;
  middlePageInstruction?: (page: number, total: number) => string;
  transitionNote?: string;
  previousSpeechHeader?: string;
  /** Agent formatting */
  agentsHeader?: string;
  /** Teacher persona */
  teacherPersonaInstruction?: (name: string) => string;
  /** Image formatting */
  imageLabelSeparator?: string;
  imageSizePrefix?: string;
  imageRatioLabel?: string;
  imagePdfSourceLabel?: string;
  imageAttachedNote?: string;
  /** Vision content */
  visionImagesHeader?: string;
  visionImagePrefix?: string;
  /** Media prompt */
  noImagesAvailable?: string;
  autoGeneratedNote?: string;
}

export const DEFAULT_PROMPT_TEMPLATES: Required<PromptTemplateConfig> = {
  courseOutlineHeader: 'Course Outline:',
  currentPageMarker: ' ← current',
  sameSessionWarning:
    'IMPORTANT: All pages belong to the SAME class session. Do NOT greet again after the first page. When referencing content from earlier pages, say "we just covered" or "as mentioned on page N" — NEVER say "last class" or "previous session" because there is no previous session.',
  firstPageInstruction: 'Position: This is the FIRST page. Open with a greeting and course introduction.',
  lastPageInstruction: 'Position: This is the LAST page. Conclude the course with a summary and closing.',
  middlePageInstruction: (page, total) =>
    `Position: Page ${page} of ${total} (middle of the course).`,
  transitionNote: 'Transition: Continue naturally from the previous page. Do NOT greet or re-introduce.',
  previousSpeechHeader: 'Previous page speech (for transition reference):',
  agentsHeader: 'Classroom Agents:',
  teacherPersonaInstruction: (name) =>
    `Teacher Persona:\nName: ${name}\n\nAdapt the content style and tone to match this teacher's personality. IMPORTANT: The teacher's name and identity must NOT appear on the slides — no "Teacher ${name}'s tips", no "Teacher's message", etc. Slides should read as neutral, professional visual aids.`,
  imageLabelSeparator: ' | ',
  imageSizePrefix: 'size: ',
  imageRatioLabel: 'aspect ratio ',
  imagePdfSourceLabel: 'from PDF page ',
  imageAttachedNote: ' [see attached]',
  visionImagesHeader: '\n\n--- Attached Images ---',
  visionImagePrefix: '\n**',
  noImagesAvailable: 'No images available. Do not insert any image elements.',
  autoGeneratedNote: '(auto-generated from key points)',
};

function t<T extends keyof Required<PromptTemplateConfig>>(
  config: PromptTemplateConfig | undefined,
  key: T,
): Required<PromptTemplateConfig>[T] {
  return (config?.[key] ?? DEFAULT_PROMPT_TEMPLATES[key]) as Required<PromptTemplateConfig>[T];
}

// ── Public functions ──

export function buildCourseContext(
  ctx?: SceneGenerationContext,
  config?: PromptTemplateConfig,
): string {
  if (!ctx) return '';

  const lines: string[] = [];

  lines.push(t(config, 'courseOutlineHeader'));
  ctx.allTitles.forEach((title, i) => {
    const marker = i === ctx.pageIndex - 1 ? t(config, 'currentPageMarker') : '';
    lines.push(`  ${i + 1}. ${title}${marker}`);
  });

  lines.push('');
  lines.push(t(config, 'sameSessionWarning'));
  lines.push('');

  if (ctx.pageIndex === 1) {
    lines.push(t(config, 'firstPageInstruction'));
  } else if (ctx.pageIndex === ctx.totalPages) {
    lines.push(t(config, 'lastPageInstruction'));
    lines.push(t(config, 'transitionNote'));
  } else {
    const fn = t(config, 'middlePageInstruction');
    lines.push(fn(ctx.pageIndex, ctx.totalPages));
    lines.push(t(config, 'transitionNote'));
  }

  if (ctx.previousSpeeches.length > 0) {
    lines.push('');
    lines.push(t(config, 'previousSpeechHeader'));
    const lastSpeech = ctx.previousSpeeches[ctx.previousSpeeches.length - 1];
    lines.push(`  "...${lastSpeech.slice(-150)}"`);
  }

  return lines.join('\n');
}

export function formatAgentsForPrompt(
  agents?: AgentInfo[],
  config?: PromptTemplateConfig,
): string {
  if (!agents || agents.length === 0) return '';

  const lines = [t(config, 'agentsHeader')];
  for (const a of agents) {
    const personaPart = a.persona ? ` — ${a.persona}` : '';
    lines.push(`- id: "${a.id}", name: "${a.name}", role: ${a.role}${personaPart}`);
  }
  return lines.join('\n');
}

export function formatTeacherPersonaForPrompt(
  agents?: AgentInfo[],
  config?: PromptTemplateConfig,
): string {
  if (!agents || agents.length === 0) return '';

  const teacher = agents.find((a) => a.role === 'teacher');
  if (!teacher?.persona) return '';

  const fn = t(config, 'teacherPersonaInstruction');
  return fn(teacher.name);
}

export function formatImageDescription(
  img: PdfImage,
  config?: PromptTemplateConfig,
): string {
  const sep = t(config, 'imageLabelSeparator');
  let dimInfo = '';
  if (img.width && img.height) {
    const ratio = (img.width / img.height).toFixed(2);
    dimInfo = `${sep}${t(config, 'imageSizePrefix')}${img.width}×${img.height} (${t(config, 'imageRatioLabel')}${ratio})`;
  }
  const desc = img.description ? `${sep}${img.description}` : '';
  return `- **${img.id}**: ${t(config, 'imagePdfSourceLabel')}${img.pageNumber}${dimInfo}${desc}`;
}

export function formatImagePlaceholder(
  img: PdfImage,
  config?: PromptTemplateConfig,
): string {
  const sep = t(config, 'imageLabelSeparator');
  let dimInfo = '';
  if (img.width && img.height) {
    const ratio = (img.width / img.height).toFixed(2);
    dimInfo = `${sep}${t(config, 'imageSizePrefix')}${img.width}×${img.height} (${t(config, 'imageRatioLabel')}${ratio})`;
  }
  return `- **${img.id}**: ${t(config, 'imagePdfSourceLabel')}${img.pageNumber}${dimInfo}${t(config, 'imageAttachedNote')}`;
}

export function buildVisionUserContent(
  userPrompt: string,
  images: Array<{ id: string; src: string; width?: number; height?: number }>,
  config?: PromptTemplateConfig,
): Array<{ type: 'text'; text: string } | { type: 'image'; image: string; mimeType?: string }> {
  const parts: Array<
    { type: 'text'; text: string } | { type: 'image'; image: string; mimeType?: string }
  > = [{ type: 'text', text: userPrompt }];
  if (images.length > 0) {
    parts.push({ type: 'text', text: t(config, 'visionImagesHeader') });
    const sep = t(config, 'imageLabelSeparator');
    const prefix = t(config, 'visionImagePrefix');
    const sizeLabel = t(config, 'imageSizePrefix');
    const ratioLabel = t(config, 'imageRatioLabel');
    for (const img of images) {
      let dimInfo = '';
      if (img.width && img.height) {
        const ratio = (img.width / img.height).toFixed(2);
        dimInfo = ` (${img.width}×${img.height}, ${ratioLabel}${ratio})`;
      }
      parts.push({ type: 'text', text: `${prefix}${img.id}**${dimInfo}:` });
      const dataUriMatch = img.src.match(/^data:([^;]+);base64,(.+)$/);
      if (dataUriMatch) {
        parts.push({
          type: 'image',
          image: dataUriMatch[2],
          mimeType: dataUriMatch[1],
        });
      } else {
        parts.push({ type: 'image', image: img.src });
      }
    }
  }
  return parts;
}

export function buildLanguageText(directive?: string, sceneNote?: string): string {
  if (!directive && !sceneNote) return '';
  let text = directive || '';
  if (sceneNote) {
    text += (text ? '\n\n' : '') + `Additional language note for this scene: ${sceneNote}`;
  }
  return text;
}

/** Convenience: get the configured default strings for use outside formatters */
export function getPromptTemplate(key: keyof PromptTemplateConfig, config?: PromptTemplateConfig): string {
  return String(t(config, key));
}
